/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AFooter: typeof import('./components/common/AFooter.vue')['default']
    AGnb: typeof import('./components/common/AGnb.vue')['default']
    AHeader: typeof import('./components/common/AHeader.vue')['default']
    ALnb: typeof import('./components/common/ALnb.vue')['default']
    LodingView: typeof import('./components/common/LodingView.vue')['default']
    MAutoSearch: typeof import('./components/common/comp/MAutoSearch.vue')['default']
    MDatePicker: typeof import('./components/common/comp/MDatePicker.vue')['default']
    MLabelInput: typeof import('./components/common/comp/MLabelInput.vue')['default']
    MLabelSelect: typeof import('./components/common/comp/MLabelSelect.vue')['default']
    MMultiSelect: typeof import('./components/common/comp/MMultiSelect.vue')['default']
    MSelect: typeof import('./components/common/comp/MSelect.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
